"""
This type stub file was generated by pyright.
"""

__all__ = ['ConvexHull', 'Delaunay', 'HalfspaceIntersection', 'QhullError', 'Voronoi', 'os', 'sys', 'tempfile', 'threading', 'tsearch']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

