"""
This type stub file was generated by pyright.
"""

"""
Pythran implementation of columns grouping for finite difference Jacobian
estimation. Used by ._numdiff.group_columns and based on the Cython version.
"""
def group_dense(m, n, A): # -> NDArray[intp]:
    ...

def group_sparse(m, n, indices, indptr): # -> NDArray[intp]:
    ...

